=== jagveer-loky/parsers/src/main/resources/booking.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="airport" type="airportType"/>
    <xs:complexType name="seatPitchType">
      <xs:simpleContent>
        <xs:extension base="xs:string">
        <xs:attribute name="units" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="widthType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="units" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="seatRowsType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="units" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="seatType">
    <xs:sequence>
      <xs:element name="seatPitch" type="seatPitchType"/>
      <xs:element name="width" type="widthType"/>
      <xs:element name="seatRows" type="seatRowsType"/>
      <xs:element name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="business"/>
            <xs:enumeration value="economy"/>
            <xs:enumeration value="first class"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="seatsType">
    <xs:sequence>
      <xs:element name="seat" type="seatType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="airplaneType">
    <xs:sequence>
      <xs:element name="model">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Airbus"/>
            <xs:enumeration value="Boing"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="capacity">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="271"/>
            <xs:enumeration value="660"/>
            <xs:enumeration value="240"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="seats" type="seatsType"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="airplanesType">
    <xs:sequence>
      <xs:element name="airplane" type="airplaneType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="airlineType">
    <xs:sequence>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Belavia"/>
            <xs:enumeration value="Turkish Airlines"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="dob">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1996-05-06"/>
            <xs:enumeration value="1933-04-20"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="airplanes" type="airplanesType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="airlinesType">
    <xs:sequence>
      <xs:element name="airline" type="airlineType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="airportType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element  name="airlines" type="airlinesType"/>
    </xs:sequence>
    <xs:attribute  name="id" type="xs:string"/>
  </xs:complexType>
</xs:schema>

=== jagveer-loky/parsers/src/main/resources/booking.xml
<?xml version="1.0" encoding="UTF-8" ?>
<airport id = "MSQ" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="booking.xsd">
    <name>Minsk National Airport</name>
    <airlines>
        <airline>
            <name>Belavia</name>
            <dob>1996-05-06</dob>
            <airplanes>
                <airplane id="1">
                    <model>Airbus</model>
                    <capacity>271</capacity>
                    <seats>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">46</width>
                            <seatRows units="cm">89</seatRows>
                            <type>business</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">46</width>
                            <seatRows units="cm">89</seatRows>
                            <type>business</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">46</width>
                            <seatRows units="cm">89</seatRows>
                            <type>business</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">43</width>
                            <seatRows units="cm">79</seatRows>
                            <type>economy</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">43</width>
                            <seatRows units="cm">79</seatRows>
                            <type>economy</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">43</width>
                            <seatRows units="cm">79</seatRows>
                            <type>economy</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">43</width>
                            <seatRows units="cm">79</seatRows>
                            <type>economy</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">43</width>
                            <seatRows units="cm">79</seatRows>
                            <type>economy</type>
                        </seat>
                    </seats>
                </airplane>
                <airplane id="2">
                    <model>Airbus</model>
                    <capacity>660</capacity>
                    <seats>
                        <seat>
                            <seatPitch units="cm">300</seatPitch>
                            <width units="cm">50</width>
                            <seatRows units="cm">100</seatRows>
                            <type>first class</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">300</seatPitch>
                            <width units="cm">50</width>
                            <seatRows units="cm">100</seatRows>
                            <type>first class</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">300</seatPitch>
                            <width units="cm">50</width>
                            <seatRows units="cm">100</seatRows>
                            <type>first class</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">46</width>
                            <seatRows units="cm">89</seatRows>
                            <type>business</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">46</width>
                            <seatRows units="cm">89</seatRows>
                            <type>business</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">46</width>
                            <seatRows units="cm">89</seatRows>
                            <type>business</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">43</width>
                            <seatRows units="cm">79</seatRows>
                            <type>economy</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">43</width>
                            <seatRows units="cm">79</seatRows>
                            <type>economy</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">43</width>
                            <seatRows units="cm">79</seatRows>
                            <type>economy</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">43</width>
                            <seatRows units="cm">79</seatRows>
                            <type>economy</type>
                        </seat>
                        <seat>
                            <seatPitch units="cm">240</seatPitch>
                            <width units="cm">43</width>
                            <seatRows units="cm">79</seatRows>
                            <type>economy</type>
                        </seat>
                    </seats>
                </airplane>
            </airplanes>
        </airline>
    <airline>
        <name>Turkish Airlines</name>
        <dob>1933-04-20</dob>
        <airplanes>
            <airplane id="1">
                <model>Boing</model>
                <capacity>240</capacity>
                <seats>
                    <seat>
                        <seatPitch units="cm">240</seatPitch>
                        <width units="cm">46</width>
                        <seatRows units="cm">89</seatRows>
                        <type>business</type>
                    </seat>
                    <seat>
                        <seatPitch units="cm">240</seatPitch>
                        <width units="cm">46</width>
                        <seatRows units="cm">89</seatRows>
                        <type>business</type>
                    </seat>
                    <seat>
                        <seatPitch units="cm">240</seatPitch>
                        <width units="cm">46</width>
                        <seatRows units="cm">89</seatRows>
                        <type>business</type>
                    </seat>
                    <seat>
                        <seatPitch units="cm">240</seatPitch>
                        <width units="cm">43</width>
                        <seatRows units="cm">79</seatRows>
                        <type>economy</type>
                    </seat>
                    <seat>
                        <seatPitch units="cm">240</seatPitch>
                        <width units="cm">43</width>
                        <seatRows units="cm">79</seatRows>
                        <type>economy</type>
                    </seat>
                    <seat>
                        <seatPitch units="cm">240</seatPitch>
                        <width units="cm">43</width>
                        <seatRows units="cm">79</seatRows>
                        <type>economy</type>
                    </seat>
                    <seat>
                        <seatPitch units="cm">240</seatPitch>
                        <width units="cm">43</width>
                        <seatRows units="cm">79</seatRows>
                        <type>economy</type>
                    </seat>
                    <seat>
                        <seatPitch units="cm">240</seatPitch>
                        <width units="cm">43</width>
                        <seatRows units="cm">79</seatRows>
                        <type>economy</type>
                    </seat>
                </seats>
            </airplane>
            <airplane id="2">
                <model>Airbus</model>
                <capacity>660</capacity>
                <seats>
                    <seat>
                        <seatPitch units="cm">300</seatPitch>
                        <width units="cm">50</width>
                        <seatRows units="cm">100</seatRows>
                        <type>first class</type>
                    </seat>
                    <seat>
                        <seatPitch units="cm">300</seatPitch>
                        <width units="cm">50</width>
                        <seatRows units="cm">100</seatRows>
                        <type>first class</type>
                    </seat>
                    <seat>
                        <seatPitch units="cm">300</seatPitch>
                        <width units="cm">50</width>
                        <seatRows units="cm">100</seatRows>
                        <type>first class</type>
                    </seat>
                    <seat>
